import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validAnswers} from '../poetry-engine.mjs';
const poems=JSON.parse(readFileSync(new URL('../public/data/poetry-top1000.json',import.meta.url)));
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:375,height:812}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
assert.equal(await page.locator('#start-screen').isVisible(),true);
assert.equal(await page.locator('#game').isVisible(),false);
await page.locator('input[value="poetry"]').check();await page.locator('#start').click();
await page.locator('.poetry-tile').first().waitFor();
let tiles=await page.locator('.poetry-tile').allTextContents();
const length=await page.locator('.poetry-slot').count();
assert.equal(tiles.length,length===5?9:12);
await page.locator('.poetry-tile').first().click();await page.locator('.poetry-slot').first().click();
assert.equal(await page.locator('.poetry-slot').first().textContent(),'');
const answer=validAnswers(poems,tiles,length)[0].line;
const used=new Set();
for(const c of answer){const i=tiles.findIndex((v,i)=>v===c&&!used.has(i));used.add(i);await page.locator('.poetry-tile').nth(i).click();}
await page.locator('#poetry-submit').click();
assert.ok((await page.locator('#poetry-source').textContent()).includes(answer));
await page.locator('#poetry-next').click();await page.locator('#poetry-reveal').click();
assert.ok((await page.locator('#poetry-source').textContent()).includes('《'));
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'/tmp/hanzi-poetry-mobile.png',fullPage:true});
await page.reload();await page.locator('#start').click();
await page.locator('#guess:not([disabled])').waitFor();
assert.equal(await page.locator('#game').isVisible(),true);
assert.deepEqual(errors,[]);
await browser.close();console.log('Browser: start screen, selection, undo, correct answer, next, reveal, mobile layout, idiom regression passed');
